# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='posts.Member')),
            ],
        ),
    ]
