# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_otherCategory',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
