# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
        migrations.AlterField(
            model_name='image1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads1/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
