# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image1',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
