# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_image1_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image1',
            name='title',
        ),
    ]
