# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_is_anonymous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authority',
        ),
    ]
