# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_member_karma_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_done', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Member')),
            ],
        ),
    ]
