# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170225_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='karma_points',
            field=models.IntegerField(default=50),
        ),
    ]
