# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_member_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationDetails',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_id', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Member')),
            ],
        ),
    ]
