# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_pushnotificationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
