# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_delete_pushnotificationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationArea',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('cen_lat', models.FloatField()),
                ('cen_lon', models.FloatField()),
                ('radius', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Member')),
            ],
        ),
    ]
