# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_notificationarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationarea',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
