# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_notificationarea_user_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('support_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Member')),
            ],
        ),
    ]
