# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Review', max_length=20),
        ),
    ]
