# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
